SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO RI JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
WHERE LEFT(ADDRESS,2)='서울'
GROUP BY REST_NAME
ORDER BY SCORE DESC, FAVORITES DESC